//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHang.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bạn có muốn đóng ứng dụng hay không?")]
        public string CONFIRM_CLOSE {
            get {
                return ((string)(this["CONFIRM_CLOSE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sai tên tài khoản hoặc mật khẩu")]
        public string checkAccount {
            get {
                return ((string)(this["checkAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thông báo!")]
        public string Notification {
            get {
                return ((string)(this["Notification"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bàn đã có người!")]
        public string SomeBody {
            get {
                return ((string)(this["SomeBody"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bàn trống không thể chuyển sang bàn trống!")]
        public string EmptyTable {
            get {
                return ((string)(this["EmptyTable"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Có lỗi khi xóa món ăn!")]
        public string ErrorDeleteFood {
            get {
                return ((string)(this["ErrorDeleteFood"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xóa món thành công")]
        public string SuccessfullDeletion {
            get {
                return ((string)(this["SuccessfullDeletion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xác nhận mật khẩu không trùng khóp. Vui lòng nhập lại mật khẩu!")]
        public string ConfirmPassword {
            get {
                return ((string)(this["ConfirmPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Không tìm thấy thông tin này!")]
        public string NotFound {
            get {
                return ((string)(this["NotFound"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vui lòng nhập password mới và xác nhận lại!")]
        public string RePasswordAndConfirm {
            get {
                return ((string)(this["RePasswordAndConfirm"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bạn có chắc thanh toán hóa đơn cho bàn {0}\\n Tổng tiền - (Tổng tiền/100)*Giảm giá" +
            "\\n => {1} - ({1}/100)x{2} = {3}đ")]
        public string Pay {
            get {
                return ((string)(this["Pay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bạn có thật sự muốn chuyển bàn {0} qua bàn {1}")]
        public string SwitchTable {
            get {
                return ((string)(this["SwitchTable"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-SBC64RI0;Initial Catalog=QUANLYNHAHANG;Integrated Security=Tru" +
            "e")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Chào mừng bạn đến với nhà hàng của chúng tôi. Một nhà hàng cao cấp 5 sao sẽ làm cho bạn hài lòng. Đến với nhà hàng của chúng tôi bạn sẽ được ăn những món ăn vô cùng tuyệt vời, khiến bạn không bao giờ quên. Ăn một lần nhớ trọn đời. Bạn còn chờ gì nữa hãy đến đây với chúng tôi.")]
        public string Introduce {
            get {
                return ((string)(this["Introduce"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Welcome to Restaurant")]
        public string Hello {
            get {
                return ((string)(this["Hello"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Khi bạn đã đăng nhập vào thì sẽ có form manager bạn có thể quản lý nhà hàng với a" +
            "dim hoặc staff tùy vào quyền mà bạn sử dụng để quản lý")]
        public string Tutorial {
            get {
                return ((string)(this["Tutorial"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hướng dẫn")]
        public string TitleTutorial {
            get {
                return ((string)(this["TitleTutorial"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ứng dụng đang mở hihi")]
        public string applicationsopen {
            get {
                return ((string)(this["applicationsopen"]));
            }
        }
    }
}
